import Link from "next/Link";
import Head from "next/head";
import styles from "./Layout.module.css";
import { Brightness6Rounded } from "@material-ui/icons";
import { useEffect, useState } from "react";

const Layout = ({ children, title = "World Ranks" }) => {
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    document.documentElement.setAttribute(
      "data-theme",
      localStorage.getItem("theme")
    );

    setTheme(localStorage.getItem("theme"));
  }, []);

  const switchTheme = () => {
    if (theme === "light") {
      saveTheme("dark");
    } else {
      saveTheme("light");
    }
  };

  const saveTheme = (theme) => {
    setTheme(theme);
    localStorage.setItem("theme", theme);
    document.documentElement.setAttribute("data-theme", theme);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <Link href="/">
          <img
            src="/images/Logo.svg"
            alt="logo"
            style={{ cursor: "pointer" }}
          />
        </Link>

        <button className={styles.themeSwitcher} onClick={switchTheme}>
          <Brightness6Rounded />
          <div className={styles.themeName}>change theme</div>
        </button>
      </header>

      <main className={styles.main}>{children}</main>

      <footer className={styles.footer}>
        Copyright 2021 | All rights reserved | Made by Infinity Founder
        <a href="#">~ Abishiek</a>
      </footer>
    </div>
  );
};

export default Layout;
